const path = require('path');

const apiSchema = 'http://localhost:4000';
const gqlTypes = 'types/gqlTypes.ts';
const warning = `
/**
 *  ⚠️ DO NOT EDIT ⚠️
 *  This file is automatically generated. Run "yarn codegen" to update.
 */
`;

module.exports = {
  overwrite: true,
  generates: {
    [path.resolve('src', gqlTypes)]: {
      schema: apiSchema,
      plugins: [{ add: { content: warning } }, 'typescript']
    },
    [`src`]: {
      schema: apiSchema,
      preset: 'near-operation-file',
      presetConfig: {
        baseTypesPath: gqlTypes,
        extension: `.types.ts`
      },
      plugins: [{ add: { content: warning } }, 'typescript-operations'],
      documents: [`src/api/**/*.ts`]
    }
  },
  hooks: {
    afterAllFileWrite: 'eslint --fix'
  }
};
