import * as Types from '../../types/gqlTypes';

/**
 *  ⚠️ DO NOT EDIT ⚠️
 *  This file is automatically generated. Run "yarn codegen" to update.
 */

export type CompaniesQueryVariables = Types.Exact<{ [key: string]: never }>;

export type CompaniesQuery = {
  __typename?: 'Query';
  companies: Array<{
    __typename?: 'Company';
    city: string;
    id: string;
    logo: string;
    name: string;
    specialties: Array<string>;
  }>;
};
