const path = require('path');

const warning = `
/**
 *  ⚠️ DO NOT EDIT ⚠️
 *  This file is automatically generated. Run "yarn codegen" to update.
 */
`;

module.exports = {
  overwrite: true,
  generates: {
    ['src/types/gqlTypes.ts']: {
      schema: path.resolve('src/typedefs'),
      plugins: [{ add: { content: warning } }, 'typescript', 'typescript-resolvers']
    }
  },
  hooks: {
    afterAllFileWrite: 'eslint --fix'
  }
};
